spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password:
  web:
    resources:
      static-locations:
        classpath: templates/
  mvc:
    view:
      suffix: ".html"
logging:
  level:
    root: info
    com.jucwang: debug
  file:
    name: log/blog-dev.log
    path:
      config :
        classpath : logback-spring.xml
#开发环境配置